version: '3'

services:

  db_postgres:
    image: postgres:15.4-alpine
    env_file: .env
    restart: always
    volumes:
      - db_postgres:/var/lib/postgresql/data

  # db_mysql:
  #   image: mysql:8.1
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   env_file: .env
  #   volumes:
  #     - my-db:/var/lib/mysql

volumes:
  db_postgres:
  # my-db: